language: node_js
node_js:
  - stable
  - "5.3"


script:
  # run build script specified in package.json
  - node server.js
  # call script for deploying of produced artifacts
  - bash ./.travis-deploy.sh